// Common action types (suffixes)
export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT',
} as const

export const PATIENT_ACTION_TYPES = {
  FETCH_PATIENTS: 'PATIENT_FETCH_PATIENTS',
  FETCH_PATIENT_BY_ID: 'PATIENT_FETCH_PATIENT_BY_ID',
  CREATE_PATIENT: 'PATIENT_CREATE_PATIENT',
  UPDATE_PATIENT: 'PATIENT_UPDATE_PATIENT',
  DELETE_PATIENT: 'PATIENT_DELETE_PATIENT',
  RESTORE_PATIENT: 'PATIENT_RESTORE_PATIENT',
  FETCH_BRANCHES: 'PATIENT_FETCH_BRANCHES',
  DUPLICATE_WARNING: 'PATIENT_DUPLICATE_WARNING',
} as const
