export { default as AuthPage } from './AuthPage/AuthPage'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Patients } from './Patients/Patients'
export { default as Profile } from './Profile/Profile'
export { default as FutureModulePage } from './Shared/FutureModulePage'
